version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: lablink-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: lablink
      MYSQL_USER: lablink
      MYSQL_PASSWORD: lablink_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: lablink-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  

  node-red:
    image: nodered/node-red
    container_name: lablink-node-red
    ports:
      - "1880:1880"
    volumes:
      - ./node-red:/data

volumes:
  mysql-data: